loader: additional fixes for Arduino_JSON
Minor fixes for Arduino_JSON library compatibility:

- '__assert_no_args' and 'exit' are actually libc symbols, so the guards
  prevented their export in certain situations.

- _exit, stdin, stdout, stderr symbols are also exported to cover the
  dynamic link case.

- an 'undefined reference to _ctype_' error occurred because the libc is
  compiled with -Os, while the sketches are NOT - this creates an issue
  because the size optimization auto-selects a different version of
  ctype functions in picolibc. -D_PICOLIBC_CTYPE_SMALL=1 forces the
  small version to be used.

Signed-off-by: Luca Burelli <l.burelli@arduino.cc>